### ISSUE TITLE
Exception in thread "SinkRunner-PollingRunner-DefaultSinkProcessor" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by syin2** [telefonicaid/fiware-cygnus#1120]
I have noticed this log several times. It will be produced once cygnus is persisting data from Orion Context Broker after 1-2 days with a notification frequency of 5 second per message. 
===========================================================
Exception in thread "SinkRunner-PollingRunner-DefaultSinkProcessor" java.lang.OutOfMemoryError: Java heap space
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2575)
        at java.lang.Class.getMethod0(Class.java:2816)
        at java.lang.Class.getMethod(Class.java:1665)
        at com.google.gson.internal.UnsafeAllocator.create(UnsafeAllocator.java:43)
        at com.google.gson.internal.ConstructorConstructor$8.<init>(ConstructorConstructor.java:160)
        at com.google.gson.internal.ConstructorConstructor.newUnsafeAllocator(ConstructorConstructor.java:159)
        at com.google.gson.internal.ConstructorConstructor.get(ConstructorConstructor.java:77)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:71)
        at com.google.gson.Gson.getAdapter(Gson.java:353)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
        at com.google.gson.Gson.getAdapter(Gson.java:353)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52)
        at com.google.gson.Gson.getAdapter(Gson.java:353)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72)
        at com.google.gson.Gson.getAdapter(Gson.java:353)
        at com.google.gson.Gson.fromJson(Gson.java:794)
        at com.google.gson.Gson.fromJson(Gson.java:761)
        at com.google.gson.Gson.fromJson(Gson.java:710)
        at com.google.gson.Gson.fromJson(Gson.java:682)
        at com.telefonica.iot.cygnus.sinks.NGSISink.parseEventBody(NGSISink.java:465)
        at com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:382)
        at com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:254)
        at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
        at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
        at java.lang.Thread.run(Thread.java:701)
Starting an ordered shutdown of Cygnus
Stopping sources
Stopping http-source (lyfecycle state=START)
All the channels are empty
Stopping channels
Stopping mysql-channel (lyfecycle state=START)
Stopping sinks
Stopping mysql-sink (lyfecycle state=START)

I also attach my configuration file here for reference.
==================================================================
cygnusagent.sources = http-source
cygnusagent.sinks = mysql-sink
cygnusagent.channels = mysql-channel

cygnusagent.sources.http-source.channels = mysql-channel
cygnusagent.sources.http-source.type = org.apache.flume.source.http.HTTPSource
cygnusagent.sources.http-source.port = 5050
cygnusagent.sources.http-source.handler = com.telefonica.iot.cygnus.handlers.NGSIRestHandler
cygnusagent.sources.http-source.handler.notification_target = /notify
cygnusagent.sources.http-source.handler.default_service = ******
cygnusagent.sources.http-source.handler.default_service_path = /
cygnusagent.sources.http-source.handler.events_ttl = 10
cygnusagent.sources.http-source.interceptors = ts gi
cygnusagent.sources.http-source.interceptors.ts.type = timestamp
cygnusagent.sources.http-source.interceptors.gi.type = com.telefonica.iot.cygnus.interceptors.NGSIGroupingInterceptor$Builder
cygnusagent.sources.http-source.interceptors.gi.grouping_rules_conf_file = /usr/cygnus/conf/grouping_rules.conf

cygnusagent.sinks.mysql-sink.channel = mysql-channel
cygnusagent.sinks.mysql-sink.type = com.telefonica.iot.cygnus.sinks.NGSIMySQLSink
cygnusagent.sinks.mysql-sink.enable_grouping = true
cygnusagent.sinks.mysql-sink.data_model = dm-by-service-path
cygnusagent.sinks.mysql-sink.table_type = dm-by-service-path
cygnusagent.sinks.mysql-sink.batch_size = 1
cygnusagent.sinks.mysql-sink.batch_timeout = 30
cygnusagent.sinks.mysql-sink.batch_ttl = 10

cygnusagent.sinks.mysql-sink.mysql_host =**************************
cygnusagent.sinks.mysql-sink.mysql_port = ****
cygnusagent.sinks.mysql-sink.mysql_username = *****
cygnusagent.sinks.mysql-sink.mysql_password = *********
cygnusagent.sinks.mysql-sink.attr_persistence = column

cygnusagent.channels.mysql-channel.type = memory
cygnusagent.channels.mysql-channel.capacity = 1000
cygnusagent.channels.mysql-channel.transactionCapacity = 100

**Comment by frbattid** [comment]
This is a problem with the Java Virtual Machine (JVM). The kind of data you are using exhauts the heap space in memory assinged to the JVM by default. This should be fixed by simply increasing the JVM heap space; please check this [link](http://stackoverflow.com/questions/1565388/increase-heap-size-in-java) for reference.

**Comment by frbattid** [comment]
Closing.
