### ISSUE TITLE
java.lang.IllegalStateException when enable name mappings on the NGSICKANSink

### ISSUE THREAD

**Issue by Javier-Paez** [telefonicaid/fiware-cygnus#1449]
[cygnus_conf.zip](https://github.com/telefonicaid/fiware-cygnus/files/1232926/cygnus_conf.zip)

Hello Team,

I'm working with Cygnus 1.7.1.0.
The Cygnus architecture is only one agent with a HTTP source, that has connected three channels: avro-channel,  mongo-channel and ckan-channel ; each channel are connected to a sink: avro-sink,  mongo-sink and ckan-sink.

The HTTP source has configured "multiplexing" and timestamp interceptors.
The sytem is working right but the dataset name in ckan.org show aditional characters then I added a name mappings interceptor; but I get this error in the cygnus log file:

> time=2017-08-17T23:03:22.446Z | lvl=ERROR | corr=f35a5cf8-839f-11e7-a37d-fa163ebd284f | trans=dfdfed51-49f5-40a0-90a8-f2c733ca35a5 | srv=usal_jp | subsrv=/Madrid/WeatherStation | comp=cygnusagent | op=run | msg=org.apache.flume.SinkRunner$PollingRunner[160] : Unable to deliver event. Exception follows.
> java.lang.IllegalStateException: begin() called when transaction is OPEN!
>         at com.google.common.base.Preconditions.checkState(Preconditions.java:145)
>         at org.apache.flume.channel.BasicTransactionSemantics.begin(BasicTransactionSemantics.java:131)
>         at com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:476)
>         at com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:368)
>         at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
>         at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
>         at java.lang.Thread.run(Thread.java:745)

I've attached the config files.
Are there something wrong in the config files?
or this issue is a bug...

Thank you in advance

**Comment by frbattid** [comment]
I'll try to reproduce the error ASAP.

Nevertheless, having a quick look to your `agent_usal.conf` file, the NameMappings interceptor is configured... but never used:

```
cygnusagent.sources.http-source.interceptors = ts
cygnusagent.sources.http-source.interceptors.ts.type = timestamp
cygnusagent.sources.http-source.interceptors.nmi.type = com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor$Builder
cygnusagent.sources.http-source.interceptors.nmi.name_mappings_conf_file = /usr/cygnus/conf/name_mappings.conf
```

It must be:

```
cygnusagent.sources.http-source.interceptors = ts nmi
cygnusagent.sources.http-source.interceptors.ts.type = timestamp
cygnusagent.sources.http-source.interceptors.nmi.type = com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor$Builder
cygnusagent.sources.http-source.interceptors.nmi.name_mappings_conf_file = /usr/cygnus/conf/name_mappings.conf
```

I.e. with `nmi` added to the `cygnusagent.sources.http-source.interceptors` list.

**Comment by Javier-Paez** [comment]
Hi Francisco,

I've changed the parameter
`cygnusagent.sinks.ckan-sink.enable_encoding = false`
Then I can see the CKAN names right.

Thank you very much

In other hand I would like to use the name mappings functionality then I've changed my config files according with your instructions; but now I'm getting other error:

```
time=2017-08-31T07:58:33.193Z | lvl=ERROR | corr= | trans= | srv= | subsrv= | comp=cygnusagent | op=run | msg=org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable[253] : Unable to start EventDrivenSourceRunner: { source:org.apache.flume.source.http.HTTPSource{name:http-source,state:IDLE} } - Exception follows.
java.lang.NullPointerException
        at com.telefonica.iot.cygnus.containers.NameMappings$ServicePathMapping.compilePatterns(NameMappings.java:187)
        at com.telefonica.iot.cygnus.containers.NameMappings$ServiceMapping.compilePatterns(NameMappings.java:120)
        at com.telefonica.iot.cygnus.containers.NameMappings.compilePatterns(NameMappings.java:53)
        at com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor.loadNameMappings(NGSINameMappingsInterceptor.java:288)
        at com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor.loadNameMappings(NGSINameMappingsInterceptor.java:252)
        at com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor.initialize(NGSINameMappingsInterceptor.java:68)
        at org.apache.flume.interceptor.InterceptorChain.initialize(InterceptorChain.java:74)
        at org.apache.flume.channel.ChannelProcessor.initialize(ChannelProcessor.java:67)
        at org.apache.flume.source.EventDrivenSourceRunner.start(EventDrivenSourceRunner.java:43)
        at org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable.run(LifecycleSupervisor.java:251)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

I've attached the config and log files of Cygnus
[Cygnus_conf_log_30AGO2017.zip](https://github.com/telefonicaid/fiware-cygnus/files/1266329/Cygnus_conf_log_30AGO2017.zip)

**Comment by fgalan** [comment]
@Javier-Paez could you elaborate on the reason to close, pls? E.g., it was solved, it is duplicated in another issue, etc.
