### ISSUE TITLE
NullPointerException when original fields are missing in name mapping configuration.

### ISSUE THREAD

**Issue by dmabtrg** [telefonicaid/fiware-cygnus#1466]
Hi,

  According to the [docs](https://fiware-cygnus.readthedocs.io/en/latest/cygnus-ngsi/installation_and_administration_guide/name_mappings/index.html#creating-your-own-name-mappings), 

  > Additionally, please observe if any of the original names is not present, then the mapping affects all the names of that type. For instance, if originalService is not present in the mapping, then the mapping affects all the FIWARE services:

  Using the latest docker image from docker hub, when the `originalService` is missing from the name mapping configuration, like in the docs example, I get the following error:

  ```
  time=2018-02-15T12:04:06.055Z | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=loadNameMappings | msg=com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor[281] : [nmi] Reading attribute mappings, Json parsed
  time=2018-02-15T12:04:06.056Z | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=loadNameMappings | msg=com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor[294] : [nmi] Reading name mappings, Json purged
  time=2018-02-15T12:04:06.057Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=run | msg=org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable[253] : Unable to start EventDrivenSourceRunner: { source:org.apache.flume.source.http.HTTPSource{name:http-source,state:IDLE} } - Exception follows.
  java.lang.NullPointerException
          at java.util.regex.Pattern.<init>(Pattern.java:1350)
          at java.util.regex.Pattern.compile(Pattern.java:1028)
          at com.telefonica.iot.cygnus.containers.NameMappings$ServiceMapping.compilePatterns(NameMappings.java:117)
          at com.telefonica.iot.cygnus.containers.NameMappings.compilePatterns(NameMappings.java:53)
          at com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor.loadNameMappings(NGSINameMappingsInterceptor.java:297)
          at com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor.loadNameMappings(NGSINameMappingsInterceptor.java:261)
          at com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor.initialize(NGSINameMappingsInterceptor.java:68)
          at org.apache.flume.interceptor.InterceptorChain.initialize(InterceptorChain.java:74)
          at org.apache.flume.channel.ChannelProcessor.initialize(ChannelProcessor.java:67)
          at org.apache.flume.source.EventDrivenSourceRunner.start(EventDrivenSourceRunner.java:43)
          at org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable.run(LifecycleSupervisor.java:251)
          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
          at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
          at java.lang.Thread.run(Thread.java:748)
  ```

  I also think that this is what could be happening in #1449.

Regards.

**Comment by dmartinezgomez** [comment]
It seems that it is a mistake in the documentation, actually, the original fields are mandatory.

Anyway, you can use a regex expression to fit "all Ids" instead of skipping originalfields.

Something like:   "^.*" or ".+"

**Comment by fgalan** [comment]
Thanks @dmartinezgomez for the feedback!

@dmabtrg has you tested the proposed solution? Does it works for you?

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/1633 (I guess). Could it be closed?

**Comment by fgalan** [comment]
Closing. If I'm wrong, please tell so and we reopen.
