### ISSUE TITLE
Cygnus-Twitter failed when upgrade to last version

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/fiware-cygnus#1583]
For missing dependencies:

```
time=2019-01-28T08:57:44.674Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | op=run | comp=Cygnus | msg=org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable[253] : Unable to start SinkRunner: { policy:org.apache.flume.sink.DefaultSinkProcessor@47b22a28 counterGroup:{ name:null counters:{} } } - Exception follows.
java.lang.NoSuchMethodError: org.apache.http.conn.scheme.Scheme.<init>(Ljava/lang/String;ILorg/apache/http/conn/scheme/SchemeSocketFactory;)V
	at org.apache.http.impl.conn.SchemeRegistryFactory.createDefault(SchemeRegistryFactory.java:50)
	at org.apache.http.impl.conn.PoolingClientConnectionManager.<init>(PoolingClientConnectionManager.java:95)
	at com.telefonica.iot.cygnus.backends.http.HttpClientFactory.<init>(HttpClientFactory.java:76)
	at com.telefonica.iot.cygnus.backends.http.HttpBackend.<init>(HttpBackend.java:94)
	at com.telefonica.iot.cygnus.backends.hdfs.HDFSBackendImplREST.<init>(HDFSBackendImplREST.java:71)
	at com.telefonica.iot.cygnus.sinks.TwitterHDFSSink.start(TwitterHDFSSink.java:263)
	at org.apache.flume.sink.DefaultSinkProcessor.start(DefaultSinkProcessor.java:46)
	at org.apache.flume.SinkRunner.start(SinkRunner.java:79)
	at org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable.run(LifecycleSupervisor.java:251)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
time=2019-01-28T08:57:44.676Z | lvl=WARN | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | op=run | comp=Cygnus | msg=org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable[260] : Component SinkRunner: { policy:org.apache.flume.sink.DefaultSinkProcessor@47b22a28 counterGroup:{ name:null counters:{} } } stopped, since it could not besuccessfully started due to missing dependencies
```

**Comment by cesarjorgemartinez** [comment]
Also, need to fix 1.9.0 version and newer.

**Comment by fgalan** [comment]
httpcore upgrade maybe is irrelevant. New finding point to flume-ng-node, updating this dependency from 1.4.0 to 1.5.2 may solve the problem.

**Comment by cesarjorgemartinez** [comment]
We need to modify the build/package processes if we upgrade the flume-ng-node to 1.9.0 because already use mvn2, then exists this requirement to download Maver packages:

https://stackoverflow.com/questions/50946420/could-not-transfer-artifact-https-repo-maven-apache-org-maven2-received-fat

```
-Dhttps.protocols=TLSv1.2
```

**Comment by fgalan** [comment]
> We need to modify the build/package processes 

Do you mean to modify build artifacts in this repo (i.e. the pom.xml file)? Or modifications in the Jenkins/Ansible/etc. space? Or both?

**Comment by cesarjorgemartinez** [comment]
I need to review in this repo and/or ansible, etc
