### ISSUE TITLE
unexpected exception instead 404 when a non valid API request

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1588]
Cygnsu response:
```
time=2019-02-07T20:32:32.974Z | lvl=WARN | corr=N/A | trans=N/A | srv=def_servpath | subsrv=/ | op=doPost | comp=Cygnus | msg=org.apache.flume.source.http.HTTPSource$FlumeHTTPServlet[192] : Deserializer threw unexpected exception. 
org.apache.http.MethodNotSupportedException: GET method not supported
        at com.telefonica.iot.cygnus.handlers.NGSIRestHandler.getEvents(NGSIRestHandler.java:264)
        at org.apache.flume.source.http.HTTPSource$FlumeHTTPServlet.doPost(HTTPSource.java:184)
        at org.apache.flume.source.http.HTTPSource$FlumeHTTPServlet.doGet(HTTPSource.java:227)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:705)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:814)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```
for a non valid API method request

**Comment by fgalan** [comment]
As far as I know, 405 Method Not Allowed should be preferred over 404 in this case. See for instance https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

In addition an `Allow: POST` header should be included in the response to tell the failing client the right method to use.
