### ISSUE TITLE
flume transaction not properly close when unexpected exceptions

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1635]
```
time=2019-05-08T09:00:18.113Z | lvl=ERROR | corr=b09e329e-716f-11e9-a468-fa163e734aab | trans=a963b9f3-4025-403c-b957-821dc408adeb | srv=matchup_vlc | subsrv=/smartcontrol | op=run | comp=Cygnus | msg=org.apache.flume.SinkRunner$PollingRunner[160] : Unable to deliver event. Exception follows.
java.lang.IllegalStateException: begin() called when transaction is OPEN!
        at com.google.common.base.Preconditions.checkState(Preconditions.java:145)
        at org.apache.flume.channel.BasicTransactionSemantics.begin(BasicTransactionSemantics.java:131)
        at com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:482)
        at com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:370)
        at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
        at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
        at java.lang.Thread.run(Thread.java:748)
```
transaction should be under a try ...catch:
https://flume.apache.org/releases/content/1.9.0/apidocs/org/apache/flume/Transaction.html

And some checks about null value should be done in sinks:
```
time=2019-05-08T09:00:13.073Z | lvl=ERROR | corr=b09e329e-716f-11e9-a468-fa163e734aab | trans=a963b9f3-4025-403c-b957-821dc408adeb | srv=matchup_vlc | subsrv=/smartcontrol | op=run | comp=Cygnus | msg=org.apache.flume.SinkRunner$PollingRunner[160] : Unable to deliver event. Exception follows.
java.lang.NullPointerException
        at com.telefonica.iot.cygnus.sinks.NGSISTHSink$STHAggregator.aggregate(NGSISTHSink.java:325)
        at com.telefonica.iot.cygnus.sinks.NGSISTHSink.persistBatch(NGSISTHSink.java:104)
        at com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:558)
        at com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:373)
        at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
        at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
        at java.lang.Thread.run(Thread.java:748)
time=2019-05-08T09:00:13.078Z | lvl=ERROR | corr=b09e329e-716f-11e9-a468-fa163e734aab | trans=a963b9f3-4025-403c-b957-821dc408adeb | srv=matchup_vlc | subsrv=/smartcontrol | op=run | comp=Cygnus | msg=org.apache.flume.SinkRunner$PollingRunner[160] : Unable to deliver event. Exception follows.
java.lang.NullPointerException
        at com.telefonica.iot.cygnus.sinks.NGSIMongoSink$RowAggregator.aggregate(NGSIMongoSink.java:234)
        at com.telefonica.iot.cygnus.sinks.NGSIMongoSink.persistBatch(NGSIMongoSink.java:125)
        at com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:558)
        at com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:370)
        at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
        at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/1636
