### ISSUE TITLE
[OrionRESTHandler] Check if Content-Type is null

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#743]
Currently, the code iterates on all the headers, without explicitely looking for `Content-Type`, but parsing the data according to the specified content type if such a header is present. The problem arises when no `Content-Type` is specified... Which is the behaviour of the code?

<b>Effort: 1 man day</b>

**Comment by pcoello25** [comment]
I've tested a notification without `--header 'Content-Type: application/json'`. In ' Cygnus' log the behaviour is like that:
```
time=2016-02-08T10:32:08.768CET | lvl=DEBUG | trans= | srv= | subsrv= | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[206] : Header host received with value localhost:5050
time=2016-02-08T10:32:08.768CET | lvl=DEBUG | trans= | srv= | subsrv= | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[206] : Header user-agent received with value curl/7.43.0
time=2016-02-08T10:32:08.769CET | lvl=DEBUG | trans= | srv= | subsrv= | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[206] : Header accept received with value application/json
time=2016-02-08T10:32:08.769CET | lvl=DEBUG | trans= | srv= | subsrv= | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[206] : Header fiware-service received with value fiservnoti
time=2016-02-08T10:32:08.769CET | lvl=DEBUG | trans= | srv= | subsrv= | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[206] : Header fiware-servicepath received with value fiservpathnoti
time=2016-02-08T10:32:08.770CET | lvl=DEBUG | trans= | srv= | subsrv= | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[206] : Header content-length received with value 695
time=2016-02-08T10:32:08.770CET | lvl=DEBUG | trans= | srv= | subsrv= | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[206] : Header content-type received with value application/x-www-form-urlencoded
time=2016-02-08T10:32:08.770CET | lvl=WARN | trans= | srv= | subsrv= | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[210] : Bad HTTP notification (application/x-www-form-urlencoded content type not supported)
time=2016-02-08T10:32:08.771CET | lvl=WARN | trans= | srv= | subsrv= | function=doPost | comp=Cygnus | msg=org.apache.flume.source.http.HTTPSource$FlumeHTTPServlet[186] : Received bad request from client. 
org.apache.flume.source.http.HTTPBadRequestException: application/x-www-form-urlencoded content type not supported
	at com.telefonica.iot.cygnus.handlers.OrionRestHandler.getEvents(OrionRestHandler.java:211)
	at org.apache.flume.source.http.HTTPSource$FlumeHTTPServlet.doPost(HTTPSource.java:184)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:814)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```
`OrionRestHandler` show us a `Bad HTTP notification (application/x-www-form-urlencoded content type not supported)` due to a missing `Content-Type`.

Besides in the notification response:
```
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 695 out of 695 bytes
< HTTP/1.1 400 Bad request from client. application/x-www-form-urlencoded content type not supported
< Content-Type: text/html; charset=iso-8859-1
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Length: 1523
< Server: Jetty(6.1.26)
< 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 400 Bad request from client. application/x-www-form-urlencoded content type not supported</title>
</head>
<body><h2>HTTP ERROR 400</h2>
<p>Problem accessing /notify. Reason:
<pre>    Bad request from client. application/x-www-form-urlencoded content type not supported</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                

</body>
</html>
* Connection #0 to host localhost left intact
```

**Comment by frbattid** [comment]
Please observe a `content-type` is efffectively sent, i.e. `application/x-www-form-urlencoded`. I guess `curl` automatically adds this value if no content type is specified.

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/749
