### ISSUE TITLE
[api] Add /groupingrules route

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#745]
As suggested by @iariasleon in https://github.com/telefonicaid/fiware-cygnus/issues/169, the following set of operations could be added to a new `/groupingrules` route:

* POST --> create a new pattern line in matching_table.conf
* GET --> return all pattern lines or only one
* PUT --> modify a pattern line
* DELETE --> remove a pattern line

**Comment by frbattid** [comment]
Partially implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/748

**Comment by frbattid** [comment]
Post development tests with regard to the managemet interface:

* No grouping interceptors has been configured:
```
$ curl -X GET "http://localhost:8081/v1/groupingrules"
404 - Missing configuration file for Grouping Rules
```
* No valid grouping rules file has been configured:
```
$ curl -X GET "http://localhost:8081/v1/groupingrules"
404 - Configuration file for Grouing Rules not found. Details: /Users/frb/devel/fiware/fiware-cygnus/conf/grouping_rules.con
```
* No rules have been configured within the grouping rules file:
```
$ curl -X GET "http://localhost:8081/v1/groupingrules"
$
..
time=2016-02-17T15:29:38.017CET | lvl=ERROR | trans= | svc= | subsvc= | function=warn | comp=Cygnus | msg=org.mortbay.log.Slf4jLog[87] : /v1/groupingrules
java.lang.NullPointerException
	at com.telefonica.iot.cygnus.interceptors.GroupingRules.toString(GroupingRules.java:158)
	at com.telefonica.iot.cygnus.management.ManagementInterface.handleGetGroupingRules(ManagementInterface.java:303)
	at com.telefonica.iot.cygnus.management.ManagementInterface.handle(ManagementInterface.java:113)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```
* The rules are not valid:
```
$ curl -X GET "http://localhost:8081/v1/groupingrules"
{"grouping_rules": []}
```
* Removing an inexistent rule:
```
$ curl -X DELETE "http://localhost:8081/v1/groupingrules?id=2"
{"success":"false"}
```
* Update an inexistent rule:
```
$ curl -X PUT "http://localhost:8081/v1/groupingrules?id=2" -d '{"regex":"Room","destination":"otherdest","fiware_service_path":"otherservpath","fields":["entityType"]}'
{"success":"false"}
```
* Add a new rule with wrong syntax:
```
$ curl -X POST "http://localhost:8081/v1/groupingrules" -d '{"egex":"Room","destination":"allrooms","fiware_service_path":"rooms","fields":["entityType"]}'
400 - Invalid grouping rule, some field is missing
```

**Comment by frbattid** [comment]
e2e tests fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/799

**Comment by frbattid** [comment]
Status codes fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/805

**Comment by frbattid** [comment]
Homegenized results in PR https://github.com/telefonicaid/fiware-cygnus/pull/813
