### ISSUE TITLE
[OrionKafkaSink] The Kafka producer does some kind of reverse name resolution despite an IP address is configured as endpoint

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#820]
This has been reported by a user:

> My kafka instance run over a virtual machine (quickstart.cloudera) and it is accessible using a public ip (hidden to the public as "publicIP").

> Here is my sink configuration:

```
cygnusagent.sinks.kafka-sink.type = com.telefonica.iot.cygnus.sinks.OrionKafkaSink
cygnusagent.sinks.kafka-sink.channel = kafka-channel
cygnusagent.sinks.kafka-sink.topic_type = topic-by-destination
cygnusagent.sinks.kafka-sink.broker_list = publicIP:9092 
cygnusagent.sinks.kafka-sink.zookeeper_endpoint = publicIP:2181
cygnusagent.sinks.kafka-sink.batch_size = 1
cygnusagent.sinks.kafka-sink.batch_timeout = 10
```

> Here is the error that I got in Cygnus:

```
Error connecting to node 0 at quickstart.cloudera:9092
```

> The quickstart.cloudera is my virtual machine name, can't figure out why Cygnus is trying to connect to it by name and not by IP address?

```
time=2016-02-22T16:38:08.813UTC | lvl=DEBUG | trans= | srv= | subsrv= | function=initiateConnect | comp=Cygnus | msg=org.apache.kafka.clients.NetworkClient[413] : Initiating connection to node 0 at quickstart.cloudera:9092.
time=2016-02-22T16:38:08.814UTC | lvl=DEBUG | trans= | srv= | subsrv= | function=initiateConnect | comp=Cygnus | msg=org.apache.kafka.clients.NetworkClient[421] : Error connecting to node 0 at quickstart.cloudera:9092:
java.io.IOException: Can't resolve address: quickstart.cloudera:9092
         at
org.apache.kafka.common.network.Selector.connect(Selector.java:138)
         at
org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:415)
         at
org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:116)
         at
org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:165)
         at
org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122)
         at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.UnresolvedAddressException
         at sun.nio.ch.Net.checkAddress(Net.java:101)
         at
sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
         at
org.apache.kafka.common.network.Selector.connect(Selector.java:135)
         ... 5 more
```

**Comment by frbattid** [comment]
Closing since this is a problem with Kafka...
